server:
  port: 8081
spring:
  application:
    name: member-client
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/project_4st
    username: swcamp
    password: swcamp
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    generate-ddl: false
    show-sql: true
    database: mysql
    hibernate:    # 쿼리가 자동으로 소문자 + 스네이크로 변경되서 생성되지 않도록 설정
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:
        '[format_sql]': true

  # 파일 설정
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB         # 업로드 할 수 있는 각 파일 용량(default 1MB)
      max-request-size: 200MB      # 업로드 요청당 총 용량(default 10MB)
  web:
    resources:
      static-locations: file:///C:/uploadFiles/     # 정적 리소스 경로
      cache-period: 3600                            # 웹 브라우저의 캐싱 시간(초, 1시간)

logging:
  level:
    com:
      ohgiraffers:
        springdatajpa: debug


token:
  secret: v7o98gdK42iddFqTxH07Yjv18KbwIZWQZu7NRPeR9+ji9tOGDX2r8PO3mGptklEdEiIB0RMT066q3qb19YBfqQ==
  expiration_time: 43200000 # 12시간



#설명. actuator를 추가하면서 설정한 내용(beans, info는 GET, refresh는 POST)
management:
  endpoints:
    web:
      exposure:
        include: refresh, beans, info
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true




# 프로필 이지미 관련 경로
profile:
  dirPath: /img/profile/